# This is a basic workflow to help you get started with Actions
name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         sudo apt update
         sudo apt install build-essential
         mkdir ~/pacman_source

         cd ~/pacman_source
         #pacman-5.1.3-1-x86_64.pkg.tar.xz 
         wget https://archive.archlinux.org/packages/p/pacman/pacman-5.1.3-1-x86_64.pkg.tar.xz        
         tar -xvf pacman-5.1.3-1-x86_64.pkg.tar.xz
         cd pacman-5.1.3-1-x86_64/.pkg.tar.xz 
         meson build
         ninja -C build
         ninja -C build install
         ./configure
         make
         sudo make install
         sudo pacman -S archiso mkinitcpio-archiso git squashfs-tools --needed
         ./prepare.sh
         sudo ./mkarchiso -v "." 2>&1 | tee "eosiso_$(date -u +'%Y.%m.%d-%H:%M').log"
